# Generated by Django 3.0.4 on 2020-03-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='preferend_language',
            new_name='preferred_language',
        ),
    ]
